
global:
  dockerBase: "us-west1-docker.pkg.dev/zerok-dev/zk-client"

kubernetesClusterDomain: cluster.local
zkAxon:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 0
  replicas: 1
  type: ClusterIP
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

postgres:
  host: "postgres.zk-client.svc.cluster.local"
  port: 5432
  password: ""
  database: "pl"
  user: "postgres"
  max_connections: 5
  max_idle_connections: 5
  connection_max_lifetime_in_minutes: 10

redis:
  host: redis.zk-client.svc.cluster.local
  port: 6379
  readTimeout: 20
  dbs:
    traces: 1
    otel: 3
    scenarios: 6
    integrations: 9

image:
  repo: "zk-axon"
  tag: "latest"
  imagePullPolicy: Always