definitions:
  dto.IncidentDto:
    properties:
      destination:
        type: string
      first_seen:
        type: string
      last_seen:
        type: string
      scenario_id:
        type: string
      scenario_type:
        type: string
      scenario_version:
        type: string
      source:
        type: string
      title:
        type: string
      total_count:
        type: integer
      velocity:
        type: number
    type: object
  dto.MetadataMapDto:
    properties:
      destination:
        type: string
      protocol_list:
        items:
          type: string
        type: array
      source:
        type: string
      trace_count:
        type: integer
    type: object
  scenariodataresponse.IncidentResponse:
    properties:
      incidents:
        items:
          $ref: '#/definitions/dto.IncidentDto'
        type: array
    type: object
  scenariodataresponse.MetadataMapResponse:
    properties:
      metadata_map_list:
        items:
          $ref: '#/definitions/dto.MetadataMapDto'
        type: array
    type: object
  scenariodataresponse.SpanDetails:
    properties:
      destination:
        type: string
      latency_ms:
        type: number
      metadata:
        type: string
      parent_span_id:
        type: string
      protocol:
        type: string
      source:
        type: string
      workload_id_list:
        items:
          type: string
        type: array
    type: object
  scenariodataresponse.SpanRawDataDetails:
    properties:
      request_payload:
        type: string
      response_payload:
        type: string
    type: object
  scenariodataresponse.SpanRawDataResponse:
    properties:
      spans:
        $ref: '#/definitions/scenariodataresponse.SpansRawDataDetailsMap'
    type: object
  scenariodataresponse.SpanResponse:
    properties:
      spans:
        $ref: '#/definitions/scenariodataresponse.SpansMetadataDetailsMap'
    type: object
  scenariodataresponse.SpansMetadataDetailsMap:
    additionalProperties:
      $ref: '#/definitions/scenariodataresponse.SpanDetails'
    type: object
  scenariodataresponse.SpansRawDataDetailsMap:
    additionalProperties:
      $ref: '#/definitions/scenariodataresponse.SpanRawDataDetails'
    type: object
  scenariodataresponse.TraceResponse:
    properties:
      trace_id_list:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
paths:
  /trace-persistence/incidents:
    get:
      consumes:
      - application/json
      description: Get Incidents grouped by scenario title, destination and scenario
        type with pagination for given source
      parameters:
      - description: Scenario Type
        in: query
        name: scenarioType
        required: true
        type: string
      - description: Source
        in: query
        name: source
        required: true
        type: string
      - description: Limit
        in: query
        name: limit
        type: string
      - description: Offset
        in: query
        name: offset
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/scenariodataresponse.IncidentResponse'
      summary: Get Incidents
      tags:
      - trace persistence
  /trace-persistence/metadata-map:
    get:
      consumes:
      - application/json
      description: Get total trace count and list of protocols between all the sources
        and destinations which encountered an error, in given duration with pagination
      parameters:
      - description: Duration
        in: query
        name: duration
        required: true
        type: string
      - description: Limit
        in: query
        name: limit
        type: string
      - description: Offset
        in: query
        name: offset
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/scenariodataresponse.MetadataMapResponse'
      summary: Get metadata map data
      tags:
      - trace persistence
  /trace-persistence/span:
    get:
      consumes:
      - application/json
      description: Get Span details for given trace id, span id with pagination. If
        span id is not provided, it will return all spans
      parameters:
      - description: Trace Id
        in: query
        name: traceId
        required: true
        type: string
      - description: Span Id
        in: query
        name: spanId
        required: true
        type: string
      - description: Limit
        in: query
        name: limit
        type: string
      - description: Offset
        in: query
        name: offset
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/scenariodataresponse.SpanResponse'
      summary: Get Span
      tags:
      - trace persistence
  /trace-persistence/span-raw-data:
    get:
      consumes:
      - application/json
      description: Get raw data for given trace id, span id with pagination
      parameters:
      - description: Trace Id
        in: query
        name: traceId
        required: true
        type: string
      - description: Span Id
        in: query
        name: spanId
        required: true
        type: string
      - description: Limit
        in: query
        name: limit
        type: string
      - description: Offset
        in: query
        name: offset
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/scenariodataresponse.SpanRawDataResponse'
      summary: Get raw data for given trace id, span id with pagination. Here raw
        data means request and response payload
      tags:
      - trace persistence
  /trace-persistence/traces:
    get:
      consumes:
      - application/json
      description: Get TraceId List for given scenario id with pagination
      parameters:
      - description: Scenario Id
        in: query
        name: scenarioId
        required: true
        type: string
      - description: Limit
        in: query
        name: limit
        type: string
      - description: Offset
        in: query
        name: offset
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/scenariodataresponse.TraceResponse'
      summary: Get Traces
      tags:
      - trace persistence
swagger: "2.0"
