apiVersion: v1
data:
  config.yaml: |

    server:
      host: localhost
      port: 80
    redis:
      host: {{ .Values.redis.host }}
      port: {{ .Values.redis.port }}
      readTimeout: {{ .Values.redis.readTimeout }}
      dbs:
        traces: {{ .Values.redis.dbs.traces }}
        otel: {{ .Values.redis.dbs.otel }}
        scenarios: {{ .Values.redis.dbs.scenarios }}
        integrations: {{ .Values.redis.dbs.integrations }}
    logs:
      color: true
      level: DEBUG
    http:
      debug: true
    postgres:
      host: {{ .Values.postgres.host }}
      port: {{ .Values.postgres.port }}
      user: {{ .Values.postgres.user }}
      password: {{ .Values.postgres.password }}
      dbname: {{ .Values.postgres.database }}
      max_connections: 5
      max_idle_connections: 5
      connection_max_lifetime_in_minutes: 10

kind: ConfigMap
metadata:
  labels:
    app: zk-axon
  name: {{ include "zk-axon.fullname" . }}
  namespace: zk-client