server:
  host: localhost
  port: 80

logs:
  color: true
  level: DEBUG

http:
  debug: true

postgres:
  host: "localhost"
  port: 5432
#  user: "postgres"
#  password: "eo1Mgtm6HI"
#  dbname: "pl"
  user: "pl"
  password: "pl"
  dbname: "zk"
  max_connections: 5
  max_idle_connections: 5
  connection_max_lifetime_in_minutes: 10